insert into endereco (rua, cidade, estado, cep) values ('57 Dahle Court', 'Birmingham', 'Alabama', '35285');
insert into endereco (rua, cidade, estado, cep) values ('806 Parkside Way', 'Birmingham', 'Alabama', '35210');
insert into endereco (rua, cidade, estado, cep) values ('4 Clove Terrace', 'Mobile', 'Alabama', '36616');
insert into endereco (rua, cidade, estado, cep) values ('52 Debra Plaza', 'Mobile', 'Alabama', '36622');
insert into endereco (rua, cidade, estado, cep) values ('10211 Pankratz Way', 'Birmingham', 'Alabama', '35215');
insert into endereco (rua, cidade, estado, cep) values ('5156 Barnett Terrace', 'Huntsville', 'Alabama', '35815');
insert into endereco (rua, cidade, estado, cep) values ('7856 Novick Park', 'Huntsville', 'Alabama', '35895');
insert into endereco (rua, cidade, estado, cep) values ('23 Green Center', 'Birmingham', 'Alabama', '35225');
insert into endereco (rua, cidade, estado, cep) values ('1264 Sachs Center', 'Mobile', 'Alabama', '36622');
insert into endereco (rua, cidade, estado, cep) values ('24651 Leroy Way', 'Mobile', 'Alabama', '36605');
insert into endereco (rua, cidade, estado, cep) values ('566 Scott Court', 'Birmingham', 'Alabama', '35279');
insert into endereco (rua, cidade, estado, cep) values ('0510 Burning Wood Hill', 'Birmingham', 'Alabama', '35285');
insert into endereco (rua, cidade, estado, cep) values ('868 Roxbury Terrace', 'Montgomery', 'Alabama', '36109');
insert into endereco (rua, cidade, estado, cep) values ('02685 Westend Junction', 'Mobile', 'Alabama', '36689');
insert into endereco (rua, cidade, estado, cep) values ('00 Donald Parkway', 'Birmingham', 'Alabama', '35279');
insert into endereco (rua, cidade, estado, cep) values ('84 Barnett Road', 'Anniston', 'Alabama', '36205');
insert into endereco (rua, cidade, estado, cep) values ('2206 Sycamore Place', 'Mobile', 'Alabama', '36610');
insert into endereco (rua, cidade, estado, cep) values ('5 Derek Junction', 'Birmingham', 'Alabama', '35215');
insert into endereco (rua, cidade, estado, cep) values ('5 Derek Center', 'Anniston', 'Alabama', '36205');
insert into endereco (rua, cidade, estado, cep) values ('618 Dexter Trail', 'Montgomery', 'Alabama', '36104');
insert into endereco (rua, cidade, estado, cep) values ('18811 Transport Place', 'Montgomery', 'Alabama', '36109');
insert into endereco (rua, cidade, estado, cep) values ('4347 Schlimgen Center', 'Gadsden', 'Alabama', '35905');
insert into endereco (rua, cidade, estado, cep) values ('5 Buena Vista Plaza', 'Birmingham', 'Alabama', '35279');
insert into endereco (rua, cidade, estado, cep) values ('51 Dottie Street', 'Mobile', 'Alabama', '36622');
insert into endereco (rua, cidade, estado, cep) values ('000 Judy Lane', 'Montgomery', 'Alabama', '36125');
insert into endereco (rua, cidade, estado, cep) values ('57829 Weeping Birch Drive', 'Gadsden', 'Alabama', '35905');
insert into endereco (rua, cidade, estado, cep) values ('3732 Ryan Junction', 'Montgomery', 'Alabama', '36109');
insert into endereco (rua, cidade, estado, cep) values ('65536 Carioca Terrace', 'Mobile', 'Alabama', '36670');
insert into endereco (rua, cidade, estado, cep) values ('584 Onsgard Drive', 'Birmingham', 'Alabama', '35295');
insert into endereco (rua, cidade, estado, cep) values ('7691 Merrick Crossing', 'Birmingham', 'Alabama', '35210');
insert into endereco (rua, cidade, estado, cep) values ('883 Kennedy Drive', 'Birmingham', 'Alabama', '35220');
insert into endereco (rua, cidade, estado, cep) values ('46 Macpherson Road', 'Birmingham', 'Alabama', '35210');
insert into endereco (rua, cidade, estado, cep) values ('9900 Main Way', 'Montgomery', 'Alabama', '36177');
insert into endereco (rua, cidade, estado, cep) values ('23 Corry Center', 'Montgomery', 'Alabama', '36114');
insert into endereco (rua, cidade, estado, cep) values ('987 Eagan Park', 'Gadsden', 'Alabama', '35905');
insert into endereco (rua, cidade, estado, cep) values ('84302 Jenifer Drive', 'Mobile', 'Alabama', '36616');
insert into endereco (rua, cidade, estado, cep) values ('72234 Onsgard Point', 'Montgomery', 'Alabama', '36109');
insert into endereco (rua, cidade, estado, cep) values ('0214 Anniversary Terrace', 'Mobile', 'Alabama', '36616');
insert into endereco (rua, cidade, estado, cep) values ('79007 Ridgeview Center', 'Huntsville', 'Alabama', '35895');
insert into endereco (rua, cidade, estado, cep) values ('9491 Grim Hill', 'Tuscaloosa', 'Alabama', '35405');
insert into endereco (rua, cidade, estado, cep) values ('4 Dunning Road', 'Birmingham', 'Alabama', '35231');
insert into endereco (rua, cidade, estado, cep) values ('42 Grasskamp Court', 'Gadsden', 'Alabama', '35905');
insert into endereco (rua, cidade, estado, cep) values ('3 Portage Center', 'Birmingham', 'Alabama', '35236');
insert into endereco (rua, cidade, estado, cep) values ('31181 West Circle', 'Montgomery', 'Alabama', '36114');
insert into endereco (rua, cidade, estado, cep) values ('1 West Drive', 'Huntsville', 'Alabama', '35815');
insert into endereco (rua, cidade, estado, cep) values ('318 Moose Circle', 'Huntsville', 'Alabama', '35805');
insert into endereco (rua, cidade, estado, cep) values ('16 Clove Hill', 'Birmingham', 'Alabama', '35231');
insert into endereco (rua, cidade, estado, cep) values ('315 Sloan Point', 'Mobile', 'Alabama', '36689');
insert into endereco (rua, cidade, estado, cep) values ('05 Drewry Terrace', 'Birmingham', 'Alabama', '35215');
insert into endereco (rua, cidade, estado, cep) values ('27 Kropf Hill', 'Mobile', 'Alabama', '36616');
insert into endereco (rua, cidade, estado, cep) values ('07 South Drive', 'Montgomery', 'Alabama', '36114');
insert into endereco (rua, cidade, estado, cep) values ('5 Darwin Trail', 'Birmingham', 'Alabama', '35210');
insert into endereco (rua, cidade, estado, cep) values ('470 Northridge Point', 'Birmingham', 'Alabama', '35285');
insert into endereco (rua, cidade, estado, cep) values ('99 Arapahoe Hill', 'Birmingham', 'Alabama', '35254');
insert into endereco (rua, cidade, estado, cep) values ('8431 Kings Plaza', 'Mobile', 'Alabama', '36628');
insert into endereco (rua, cidade, estado, cep) values ('467 Autumn Leaf Junction', 'Montgomery', 'Alabama', '36134');
insert into endereco (rua, cidade, estado, cep) values ('669 Novick Way', 'Birmingham', 'Alabama', '35236');
insert into endereco (rua, cidade, estado, cep) values ('4803 Lyons Hill', 'Tuscaloosa', 'Alabama', '35487');
insert into endereco (rua, cidade, estado, cep) values ('3664 Linden Avenue', 'Birmingham', 'Alabama', '35225');
insert into endereco (rua, cidade, estado, cep) values ('800 7th Drive', 'Montgomery', 'Alabama', '36125');
insert into endereco (rua, cidade, estado, cep) values ('68 Manitowish Avenue', 'Birmingham', 'Alabama', '35279');
insert into endereco (rua, cidade, estado, cep) values ('24077 4th Point', 'Birmingham', 'Alabama', '35215');
insert into endereco (rua, cidade, estado, cep) values ('060 Towne Center', 'Mobile', 'Alabama', '36641');
insert into endereco (rua, cidade, estado, cep) values ('35 Namekagon Court', 'Birmingham', 'Alabama', '35254');
insert into endereco (rua, cidade, estado, cep) values ('9 Lawn Point', 'Birmingham', 'Alabama', '35285');
insert into endereco (rua, cidade, estado, cep) values ('768 Bluestem Junction', 'Montgomery', 'Alabama', '36195');
insert into endereco (rua, cidade, estado, cep) values ('41 Spaight Center', 'Mobile', 'Alabama', '36616');
insert into endereco (rua, cidade, estado, cep) values ('7075 Eagan Crossing', 'Birmingham', 'Alabama', '35215');
insert into endereco (rua, cidade, estado, cep) values ('89126 Mayfield Terrace', 'Tuscaloosa', 'Alabama', '35405');
insert into endereco (rua, cidade, estado, cep) values ('3 Mosinee Point', 'Mobile', 'Alabama', '36628');
insert into endereco (rua, cidade, estado, cep) values ('80960 Scott Parkway', 'Birmingham', 'Alabama', '35205');
insert into endereco (rua, cidade, estado, cep) values ('060 Shelley Lane', 'Birmingham', 'Alabama', '35231');
insert into endereco (rua, cidade, estado, cep) values ('8 Oak Valley Hill', 'Montgomery', 'Alabama', '36119');
insert into endereco (rua, cidade, estado, cep) values ('319 Manley Way', 'Birmingham', 'Alabama', '35205');
insert into endereco (rua, cidade, estado, cep) values ('8249 Wayridge Road', 'Montgomery', 'Alabama', '36177');
insert into endereco (rua, cidade, estado, cep) values ('23240 Sunnyside Plaza', 'Birmingham', 'Alabama', '35215');
insert into endereco (rua, cidade, estado, cep) values ('99 Orin Crossing', 'Anniston', 'Alabama', '36205');
insert into endereco (rua, cidade, estado, cep) values ('39164 Hanover Point', 'Mobile', 'Alabama', '36689');
insert into endereco (rua, cidade, estado, cep) values ('906 Kingsford Circle', 'Birmingham', 'Alabama', '35205');
insert into endereco (rua, cidade, estado, cep) values ('9353 Doe Crossing Pass', 'Birmingham', 'Alabama', '35263');
insert into endereco (rua, cidade, estado, cep) values ('5 Mariners Cove Pass', 'Birmingham', 'Alabama', '35244');
insert into endereco (rua, cidade, estado, cep) values ('145 Warrior Place', 'Mobile', 'Alabama', '36622');
insert into endereco (rua, cidade, estado, cep) values ('1295 Oak Plaza', 'Mobile', 'Alabama', '36610');
insert into endereco (rua, cidade, estado, cep) values ('12 Springs Street', 'Montgomery', 'Alabama', '36109');
insert into endereco (rua, cidade, estado, cep) values ('212 Clemons Avenue', 'Huntsville', 'Alabama', '35810');
insert into endereco (rua, cidade, estado, cep) values ('91861 Cardinal Lane', 'Mobile', 'Alabama', '36689');
insert into endereco (rua, cidade, estado, cep) values ('24 Mendota Alley', 'Tuscaloosa', 'Alabama', '35487');
insert into endereco (rua, cidade, estado, cep) values ('77 Walton Junction', 'Birmingham', 'Alabama', '35210');
insert into endereco (rua, cidade, estado, cep) values ('897 Rigney Center', 'Montgomery', 'Alabama', '36109');
insert into endereco (rua, cidade, estado, cep) values ('668 Loftsgordon Road', 'Birmingham', 'Alabama', '35244');
insert into endereco (rua, cidade, estado, cep) values ('330 Waxwing Way', 'Birmingham', 'Alabama', '35231');
insert into endereco (rua, cidade, estado, cep) values ('24 Ruskin Plaza', 'Mobile', 'Alabama', '36689');
insert into endereco (rua, cidade, estado, cep) values ('91468 Utah Junction', 'Gadsden', 'Alabama', '35905');
insert into endereco (rua, cidade, estado, cep) values ('01080 Shasta Park', 'Mobile', 'Alabama', '36628');
insert into endereco (rua, cidade, estado, cep) values ('2536 American Ash Terrace', 'Birmingham', 'Alabama', '35295');
insert into endereco (rua, cidade, estado, cep) values ('4220 Clyde Gallagher Pass', 'Huntsville', 'Alabama', '35805');
insert into endereco (rua, cidade, estado, cep) values ('303 Lakewood Gardens Circle', 'Birmingham', 'Alabama', '35244');
insert into endereco (rua, cidade, estado, cep) values ('41817 Hoepker Pass', 'Mobile', 'Alabama', '36622');
insert into endereco (rua, cidade, estado, cep) values ('9066 Moulton Way', 'Birmingham', 'Alabama', '35225');
insert into endereco (rua, cidade, estado, cep) values ('791 Colorado Center', 'Mobile', 'Alabama', '36628');
insert into endereco (rua, cidade, estado, cep) values ('2 Glendale Drive', 'Birmingham', 'Alabama', '35210');
insert into endereco (rua, cidade, estado, cep) values ('8907 Mayer Park', 'Huntsville', 'Alabama', '35815');
insert into endereco (rua, cidade, estado, cep) values ('9759 Corscot Center', 'Birmingham', 'Alabama', '35285');
insert into endereco (rua, cidade, estado, cep) values ('545 Graceland Pass', 'Montgomery', 'Alabama', '36114');
insert into endereco (rua, cidade, estado, cep) values ('862 Lunder Crossing', 'Montgomery', 'Alabama', '36104');
insert into endereco (rua, cidade, estado, cep) values ('12742 Northridge Trail', 'Huntsville', 'Alabama', '35810');
insert into endereco (rua, cidade, estado, cep) values ('073 Emmet Alley', 'Birmingham', 'Alabama', '35279');
insert into endereco (rua, cidade, estado, cep) values ('038 Grayhawk Trail', 'Montgomery', 'Alabama', '36125');
insert into endereco (rua, cidade, estado, cep) values ('1 Springview Terrace', 'Birmingham', 'Alabama', '35254');
insert into endereco (rua, cidade, estado, cep) values ('775 Fordem Circle', 'Mobile', 'Alabama', '36605');
insert into endereco (rua, cidade, estado, cep) values ('30 Almo Crossing', 'Mobile', 'Alabama', '36610');
insert into endereco (rua, cidade, estado, cep) values ('147 Prentice Plaza', 'Birmingham', 'Alabama', '35254');
insert into endereco (rua, cidade, estado, cep) values ('36364 Nevada Junction', 'Birmingham', 'Alabama', '35210');
insert into endereco (rua, cidade, estado, cep) values ('96697 Shoshone Circle', 'Montgomery', 'Alabama', '36104');
insert into endereco (rua, cidade, estado, cep) values ('822 Veith Alley', 'Huntsville', 'Alabama', '35815');
insert into endereco (rua, cidade, estado, cep) values ('53 Pankratz Center', 'Birmingham', 'Alabama', '35254');
insert into endereco (rua, cidade, estado, cep) values ('10 Shasta Crossing', 'Anniston', 'Alabama', '36205');
insert into endereco (rua, cidade, estado, cep) values ('38638 Susan Way', 'Huntsville', 'Alabama', '35895');
insert into endereco (rua, cidade, estado, cep) values ('18914 Farragut Hill', 'Birmingham', 'Alabama', '35225');
insert into endereco (rua, cidade, estado, cep) values ('23 Katie Way', 'Anniston', 'Alabama', '36205');
insert into endereco (rua, cidade, estado, cep) values ('75 Anderson Place', 'Mobile', 'Alabama', '36628');
insert into endereco (rua, cidade, estado, cep) values ('6 Clove Circle', 'Birmingham', 'Alabama', '35205');
insert into endereco (rua, cidade, estado, cep) values ('97389 Reinke Road', 'Birmingham', 'Alabama', '35205');
insert into endereco (rua, cidade, estado, cep) values ('296 Dennis Way', 'Tuscaloosa', 'Alabama', '35405');
insert into endereco (rua, cidade, estado, cep) values ('54078 Westend Plaza', 'Birmingham', 'Alabama', '35220');
insert into endereco (rua, cidade, estado, cep) values ('17 Clyde Gallagher Circle', 'Montgomery', 'Alabama', '36125');
insert into endereco (rua, cidade, estado, cep) values ('6589 Goodland Place', 'Mobile', 'Alabama', '36610');
insert into endereco (rua, cidade, estado, cep) values ('6933 Holy Cross Court', 'Montgomery', 'Alabama', '36119');
insert into endereco (rua, cidade, estado, cep) values ('9 East Plaza', 'Birmingham', 'Alabama', '35244');
insert into endereco (rua, cidade, estado, cep) values ('6959 Carberry Drive', 'Huntsville', 'Alabama', '35810');
insert into endereco (rua, cidade, estado, cep) values ('54768 Roxbury Hill', 'Montgomery', 'Alabama', '36195');
insert into endereco (rua, cidade, estado, cep) values ('61 Surrey Junction', 'Birmingham', 'Alabama', '35254');
insert into endereco (rua, cidade, estado, cep) values ('487 Eastlawn Circle', 'Gadsden', 'Alabama', '35905');
insert into endereco (rua, cidade, estado, cep) values ('77983 Banding Circle', 'Mobile', 'Alabama', '36622');
insert into endereco (rua, cidade, estado, cep) values ('4 Schiller Junction', 'Huntsville', 'Alabama', '35805');
insert into endereco (rua, cidade, estado, cep) values ('69 Anderson Way', 'Montgomery', 'Alabama', '36114');
insert into endereco (rua, cidade, estado, cep) values ('7743 Monterey Center', 'Mobile', 'Alabama', '36610');
insert into endereco (rua, cidade, estado, cep) values ('206 Golf View Place', 'Birmingham', 'Alabama', '35254');
insert into endereco (rua, cidade, estado, cep) values ('74 Veith Junction', 'Huntsville', 'Alabama', '35805');
insert into endereco (rua, cidade, estado, cep) values ('363 Jackson Terrace', 'Mobile', 'Alabama', '36616');
insert into endereco (rua, cidade, estado, cep) values ('7 Fairview Drive', 'Mobile', 'Alabama', '36605');
insert into endereco (rua, cidade, estado, cep) values ('42 Autumn Leaf Plaza', 'Birmingham', 'Alabama', '35205');
insert into endereco (rua, cidade, estado, cep) values ('9 Dunning Lane', 'Montgomery', 'Alabama', '36104');
insert into endereco (rua, cidade, estado, cep) values ('94 Mitchell Street', 'Birmingham', 'Alabama', '35242');
insert into endereco (rua, cidade, estado, cep) values ('6 Schurz Junction', 'Huntsville', 'Alabama', '35805');
insert into endereco (rua, cidade, estado, cep) values ('61459 Caliangt Trail', 'Birmingham', 'Alabama', '35236');
insert into endereco (rua, cidade, estado, cep) values ('1613 Mcbride Court', 'Montgomery', 'Alabama', '36119');
insert into endereco (rua, cidade, estado, cep) values ('18 Birchwood Alley', 'Mobile', 'Alabama', '36610');
insert into endereco (rua, cidade, estado, cep) values ('2690 Reinke Pass', 'Birmingham', 'Alabama', '35210');
insert into endereco (rua, cidade, estado, cep) values ('2475 Mcbride Point', 'Birmingham', 'Alabama', '35242');
insert into endereco (rua, cidade, estado, cep) values ('301 Straubel Plaza', 'Birmingham', 'Alabama', '35210');
insert into endereco (rua, cidade, estado, cep) values ('408 Heffernan Alley', 'Huntsville', 'Alabama', '35805');
insert into endereco (rua, cidade, estado, cep) values ('341 Arizona Parkway', 'Montgomery', 'Alabama', '36195');
insert into endereco (rua, cidade, estado, cep) values ('55 Hollow Ridge Junction', 'Birmingham', 'Alabama', '35205');
insert into endereco (rua, cidade, estado, cep) values ('48464 Forest Dale Hill', 'Huntsville', 'Alabama', '35805');
insert into endereco (rua, cidade, estado, cep) values ('2 Oxford Street', 'Montgomery', 'Alabama', '36109');
insert into endereco (rua, cidade, estado, cep) values ('8 Hauk Street', 'Tuscaloosa', 'Alabama', '35487');
insert into endereco (rua, cidade, estado, cep) values ('45 Hanover Parkway', 'Birmingham', 'Alabama', '35225');
insert into endereco (rua, cidade, estado, cep) values ('51783 Mosinee Court', 'Huntsville', 'Alabama', '35815');
insert into endereco (rua, cidade, estado, cep) values ('9 Drewry Point', 'Birmingham', 'Alabama', '35231');
insert into endereco (rua, cidade, estado, cep) values ('896 Stuart Crossing', 'Montgomery', 'Alabama', '36134');
insert into endereco (rua, cidade, estado, cep) values ('994 Boyd Park', 'Birmingham', 'Alabama', '35295');
insert into endereco (rua, cidade, estado, cep) values ('299 Vidon Crossing', 'Mobile', 'Alabama', '36616');
insert into endereco (rua, cidade, estado, cep) values ('6 Becker Court', 'Birmingham', 'Alabama', '35254');
insert into endereco (rua, cidade, estado, cep) values ('213 East Place', 'Birmingham', 'Alabama', '35244');
insert into endereco (rua, cidade, estado, cep) values ('4 Shelley Plaza', 'Mobile', 'Alabama', '36605');
insert into endereco (rua, cidade, estado, cep) values ('288 Autumn Leaf Center', 'Birmingham', 'Alabama', '35225');
insert into endereco (rua, cidade, estado, cep) values ('73 Porter Point', 'Birmingham', 'Alabama', '35225');
insert into endereco (rua, cidade, estado, cep) values ('35 Forest Dale Pass', 'Birmingham', 'Alabama', '35254');
insert into endereco (rua, cidade, estado, cep) values ('22174 Lakeland Plaza', 'Mobile', 'Alabama', '36628');
insert into endereco (rua, cidade, estado, cep) values ('47232 Golf Course Avenue', 'Huntsville', 'Alabama', '35815');
insert into endereco (rua, cidade, estado, cep) values ('78 Sherman Street', 'Montgomery', 'Alabama', '36177');
insert into endereco (rua, cidade, estado, cep) values ('1445 Elmside Point', 'Montgomery', 'Alabama', '36114');
insert into endereco (rua, cidade, estado, cep) values ('90 Bartelt Parkway', 'Montgomery', 'Alabama', '36114');
insert into endereco (rua, cidade, estado, cep) values ('6 Dawn Point', 'Mobile', 'Alabama', '36670');
insert into endereco (rua, cidade, estado, cep) values ('0749 Acker Circle', 'Birmingham', 'Alabama', '35205');
insert into endereco (rua, cidade, estado, cep) values ('66754 Namekagon Drive', 'Montgomery', 'Alabama', '36134');
insert into endereco (rua, cidade, estado, cep) values ('12 Veith Road', 'Montgomery', 'Alabama', '36109');
insert into endereco (rua, cidade, estado, cep) values ('90 Northwestern Crossing', 'Birmingham', 'Alabama', '35279');
insert into endereco (rua, cidade, estado, cep) values ('74723 Lighthouse Bay Lane', 'Mobile', 'Alabama', '36616');
insert into endereco (rua, cidade, estado, cep) values ('7603 Quincy Circle', 'Huntsville', 'Alabama', '35810');
insert into endereco (rua, cidade, estado, cep) values ('333 Pierstorff Terrace', 'Montgomery', 'Alabama', '36177');
insert into endereco (rua, cidade, estado, cep) values ('9048 Farragut Junction', 'Mobile', 'Alabama', '36689');
insert into endereco (rua, cidade, estado, cep) values ('7 Superior Avenue', 'Birmingham', 'Alabama', '35210');
insert into endereco (rua, cidade, estado, cep) values ('8 Meadow Ridge Way', 'Montgomery', 'Alabama', '36109');
insert into endereco (rua, cidade, estado, cep) values ('2288 Dwight Drive', 'Montgomery', 'Alabama', '36114');
insert into endereco (rua, cidade, estado, cep) values ('4563 Riverside Center', 'Montgomery', 'Alabama', '36195');
insert into endereco (rua, cidade, estado, cep) values ('9000 Oxford Way', 'Birmingham', 'Alabama', '35263');
insert into endereco (rua, cidade, estado, cep) values ('6984 Schlimgen Circle', 'Montgomery', 'Alabama', '36195');
insert into endereco (rua, cidade, estado, cep) values ('182 Westerfield Circle', 'Mobile', 'Alabama', '36641');
insert into endereco (rua, cidade, estado, cep) values ('71349 Mcbride Park', 'Huntsville', 'Alabama', '35810');
insert into endereco (rua, cidade, estado, cep) values ('8 Sunbrook Hill', 'Montgomery', 'Alabama', '36177');
insert into endereco (rua, cidade, estado, cep) values ('77 Caliangt Avenue', 'Mobile', 'Alabama', '36616');
insert into endereco (rua, cidade, estado, cep) values ('9 Chive Alley', 'Birmingham', 'Alabama', '35215');
insert into endereco (rua, cidade, estado, cep) values ('95 Quincy Point', 'Montgomery', 'Alabama', '36119');
insert into endereco (rua, cidade, estado, cep) values ('2 Grim Center', 'Montgomery', 'Alabama', '36104');
insert into endereco (rua, cidade, estado, cep) values ('032 Oak Alley', 'Anniston', 'Alabama', '36205');
insert into endereco (rua, cidade, estado, cep) values ('1671 Mesta Alley', 'Birmingham', 'Alabama', '35220');
insert into endereco (rua, cidade, estado, cep) values ('88869 Bowman Point', 'Birmingham', 'Alabama', '35285');
insert into endereco (rua, cidade, estado, cep) values ('92 Oriole Road', 'Birmingham', 'Alabama', '35244');
