insert into especie (tipo_especie) values ('Lesser masked weaver');
insert into especie (tipo_especie) values ('Civet, small-toothed palm');
insert into especie (tipo_especie) values ('Flicker, field');
insert into especie (tipo_especie) values ('Raccoon dog');
insert into especie (tipo_especie) values ('House sparrow');
insert into especie (tipo_especie) values ('White-bellied sea eagle');
insert into especie (tipo_especie) values ('Spurfowl, yellow-necked');
insert into especie (tipo_especie) values ('Moose');
insert into especie (tipo_especie) values ('Two-banded monitor');
insert into especie (tipo_especie) values ('Rattlesnake, horned');
insert into especie (tipo_especie) values ('Sungazer, yellow-brown');
insert into especie (tipo_especie) values ('Giant armadillo');
insert into especie (tipo_especie) values ('Cat, jungle');
insert into especie (tipo_especie) values ('Plains zebra');
insert into especie (tipo_especie) values ('Jackal, silver-backed');
insert into especie (tipo_especie) values ('Feral rock pigeon');
insert into especie (tipo_especie) values ('Eagle, white-bellied sea');
insert into especie (tipo_especie) values ('Fox, cape');
insert into especie (tipo_especie) values ('Yellow-bellied marmot');
insert into especie (tipo_especie) values ('Pelican, eastern white');
insert into especie (tipo_especie) values ('Lesser mouse lemur');
insert into especie (tipo_especie) values ('Heron, gray');
insert into especie (tipo_especie) values ('Skunk, striped');
insert into especie (tipo_especie) values ('Goose, greylag');
insert into especie (tipo_especie) values ('Azara''s zorro');
insert into especie (tipo_especie) values ('Carmine bee-eater');
insert into especie (tipo_especie) values ('Grizzly bear');
insert into especie (tipo_especie) values ('Hornbill, yellow-billed');
insert into especie (tipo_especie) values ('Cockatoo, slender-billed');
insert into especie (tipo_especie) values ('Crake, african black');
insert into especie (tipo_especie) values ('Crab-eating raccoon');
insert into especie (tipo_especie) values ('Southern brown bandicoot');
insert into especie (tipo_especie) values ('Cobra, egyptian');
insert into especie (tipo_especie) values ('Dove, galapagos');
insert into especie (tipo_especie) values ('Banded mongoose');
insert into especie (tipo_especie) values ('Sheep, red');
insert into especie (tipo_especie) values ('Coatimundi, ring-tailed');
insert into especie (tipo_especie) values ('Platypus');
insert into especie (tipo_especie) values ('American bison');
insert into especie (tipo_especie) values ('Stork, black-necked');
insert into especie (tipo_especie) values ('Turtle (unidentified)');
insert into especie (tipo_especie) values ('Tamandua, southern');
insert into especie (tipo_especie) values ('Yellow mongoose');
insert into especie (tipo_especie) values ('Gull, herring');
insert into especie (tipo_especie) values ('Buffalo, american');
insert into especie (tipo_especie) values ('Grizzly bear');
insert into especie (tipo_especie) values ('Violet-crested turaco');
insert into especie (tipo_especie) values ('Cat, toddy');
insert into especie (tipo_especie) values ('Scottish highland cow');
insert into especie (tipo_especie) values ('Red-tailed wambenger');
insert into especie (tipo_especie) values ('Buffalo, asian water');
insert into especie (tipo_especie) values ('Monitor, water');
insert into especie (tipo_especie) values ('Oriental white-backed vulture');
insert into especie (tipo_especie) values ('Plover, blacksmith');
insert into especie (tipo_especie) values ('Brocket, red');
insert into especie (tipo_especie) values ('Baboon, yellow');
insert into especie (tipo_especie) values ('Gull, lava');
insert into especie (tipo_especie) values ('Leopard');
insert into especie (tipo_especie) values ('Mongoose, javan gold-spotted');
insert into especie (tipo_especie) values ('Ovenbird');
insert into especie (tipo_especie) values ('Rock dove');
insert into especie (tipo_especie) values ('Mallard');
insert into especie (tipo_especie) values ('Beaver, american');
insert into especie (tipo_especie) values ('Gerbil (unidentified)');
insert into especie (tipo_especie) values ('Heron, yellow-crowned night');
insert into especie (tipo_especie) values ('Purple grenadier');
insert into especie (tipo_especie) values ('Common boubou shrike');
insert into especie (tipo_especie) values ('Galapagos dove');
insert into especie (tipo_especie) values ('Tree porcupine');
insert into especie (tipo_especie) values ('Agama lizard (unidentified)');
insert into especie (tipo_especie) values ('Seal, southern elephant');
insert into especie (tipo_especie) values ('Honey badger');
insert into especie (tipo_especie) values ('Golden jackal');
insert into especie (tipo_especie) values ('Scottish highland cow');
insert into especie (tipo_especie) values ('Hyena, brown');
insert into especie (tipo_especie) values ('Mockingbird, galapagos');
insert into especie (tipo_especie) values ('Whale, southern right');
insert into especie (tipo_especie) values ('Egyptian viper');
insert into especie (tipo_especie) values ('Sambar');
insert into especie (tipo_especie) values ('Tawny eagle');
insert into especie (tipo_especie) values ('Amazon parrot (unidentified)');
insert into especie (tipo_especie) values ('White spoonbill');
insert into especie (tipo_especie) values ('Heron, green');
insert into especie (tipo_especie) values ('Water monitor');
insert into especie (tipo_especie) values ('Flycatcher, tyrant');
insert into especie (tipo_especie) values ('Hornbill, southern ground');
insert into especie (tipo_especie) values ('Gnu, brindled');
insert into especie (tipo_especie) values ('Booby, masked');
insert into especie (tipo_especie) values ('Grey-footed squirrel');
insert into especie (tipo_especie) values ('Ringtail cat');
insert into especie (tipo_especie) values ('Baboon, gelada');
insert into especie (tipo_especie) values ('Colobus, white-mantled');
insert into especie (tipo_especie) values ('Laughing kookaburra');
insert into especie (tipo_especie) values ('Frog (unidentified)');
insert into especie (tipo_especie) values ('Gaur');
insert into especie (tipo_especie) values ('Coqui partridge');
insert into especie (tipo_especie) values ('Brocket, brown');
insert into especie (tipo_especie) values ('White-winged black tern');
insert into especie (tipo_especie) values ('White-winged tern');
insert into especie (tipo_especie) values ('American woodcock');
insert into especie (tipo_especie) values ('Rhinoceros, black');
insert into especie (tipo_especie) values ('Puna ibis');
insert into especie (tipo_especie) values ('Andean goose');
insert into especie (tipo_especie) values ('Legaan, ground');
insert into especie (tipo_especie) values ('Vulture, white-rumped');
insert into especie (tipo_especie) values ('Wallaby, red-necked');
insert into especie (tipo_especie) values ('Cockatoo, sulfur-crested');
insert into especie (tipo_especie) values ('Anaconda (unidentified)');
insert into especie (tipo_especie) values ('Heron, grey');
insert into especie (tipo_especie) values ('Porcupine, crested');
insert into especie (tipo_especie) values ('Buttermilk snake');
insert into especie (tipo_especie) values ('Pale-throated three-toed sloth');
insert into especie (tipo_especie) values ('Eagle, golden');
insert into especie (tipo_especie) values ('Pampa gray fox');
insert into especie (tipo_especie) values ('Fat-tailed dunnart');
insert into especie (tipo_especie) values ('Rhinoceros, white');
insert into especie (tipo_especie) values ('Red-billed tropic bird');
insert into especie (tipo_especie) values ('Lion, mountain');
insert into especie (tipo_especie) values ('Boa, emerald green tree');
insert into especie (tipo_especie) values ('Badger, american');
insert into especie (tipo_especie) values ('Tortoise, burmese brown mountain');
insert into especie (tipo_especie) values ('Bird, magnificent frigate');
insert into especie (tipo_especie) values ('Golden eagle');
insert into especie (tipo_especie) values ('Javan gold-spotted mongoose');
insert into especie (tipo_especie) values ('House sparrow');
insert into especie (tipo_especie) values ('Pelican, great white');
insert into especie (tipo_especie) values ('Tern, white-winged');
insert into especie (tipo_especie) values ('Lizard, desert spiny');
insert into especie (tipo_especie) values ('Barbet, black-collared');
insert into especie (tipo_especie) values ('Mississippi alligator');
insert into especie (tipo_especie) values ('Squirrel, indian giant');
insert into especie (tipo_especie) values ('Savanna baboon');
insert into especie (tipo_especie) values ('African polecat');
insert into especie (tipo_especie) values ('Blesbok');
insert into especie (tipo_especie) values ('Hummingbird (unidentified)');
insert into especie (tipo_especie) values ('Hyrax');
insert into especie (tipo_especie) values ('Indian tree pie');
insert into especie (tipo_especie) values ('Canada goose');
insert into especie (tipo_especie) values ('Eurasian beaver');
insert into especie (tipo_especie) values ('Otter, small-clawed');
insert into especie (tipo_especie) values ('Blue-tongued skink');
insert into especie (tipo_especie) values ('Shrike, crimson-breasted');
insert into especie (tipo_especie) values ('Barbet, black-collared');
insert into especie (tipo_especie) values ('Dama wallaby');
insert into especie (tipo_especie) values ('Black-throated butcher bird');
insert into especie (tipo_especie) values ('Rhinoceros, white');
insert into especie (tipo_especie) values ('Australian magpie');
insert into especie (tipo_especie) values ('Wolf, mexican');
insert into especie (tipo_especie) values ('Levaillant''s barbet');
insert into especie (tipo_especie) values ('Yellow-rumped siskin');
insert into especie (tipo_especie) values ('Black-tailed deer');
insert into especie (tipo_especie) values ('Bat, little brown');
insert into especie (tipo_especie) values ('Pacific gull');
insert into especie (tipo_especie) values ('Colobus, magistrate black');
insert into especie (tipo_especie) values ('Tailless tenrec');
insert into especie (tipo_especie) values ('Burmese black mountain tortoise');
insert into especie (tipo_especie) values ('Nelson ground squirrel');
insert into especie (tipo_especie) values ('Little grebe');
insert into especie (tipo_especie) values ('Gull, herring');
insert into especie (tipo_especie) values ('Eagle owl (unidentified)');
insert into especie (tipo_especie) values ('Butterfly (unidentified)');
insert into especie (tipo_especie) values ('Sloth bear');
insert into especie (tipo_especie) values ('Wildebeest, blue');
insert into especie (tipo_especie) values ('Meerkat, red');
insert into especie (tipo_especie) values ('Goose, knob-nosed');
insert into especie (tipo_especie) values ('Fringe-eared oryx');
insert into especie (tipo_especie) values ('Bulbul, black-eyed');
insert into especie (tipo_especie) values ('Wombat, southern hairy-nosed');
insert into especie (tipo_especie) values ('Red-necked wallaby');
insert into especie (tipo_especie) values ('Currasow (unidentified)');
insert into especie (tipo_especie) values ('Agouti');
insert into especie (tipo_especie) values ('Cattle egret');
insert into especie (tipo_especie) values ('Darwin ground finch (unidentified)');
insert into especie (tipo_especie) values ('Waved albatross');
insert into especie (tipo_especie) values ('Sociable weaver');
insert into especie (tipo_especie) values ('Ovenbird');
insert into especie (tipo_especie) values ('Indian tree pie');
insert into especie (tipo_especie) values ('African elephant');
insert into especie (tipo_especie) values ('Black-crowned night heron');
insert into especie (tipo_especie) values ('Pygmy possum');
insert into especie (tipo_especie) values ('Asian lion');
insert into especie (tipo_especie) values ('Meerkat');
insert into especie (tipo_especie) values ('Frilled dragon');
insert into especie (tipo_especie) values ('Red deer');
insert into especie (tipo_especie) values ('Galapagos mockingbird');
insert into especie (tipo_especie) values ('Gazelle, grant''s');
insert into especie (tipo_especie) values ('Cougar');
insert into especie (tipo_especie) values ('Eagle, tawny');
insert into especie (tipo_especie) values ('Crab-eating raccoon');
insert into especie (tipo_especie) values ('Feathertail glider');
insert into especie (tipo_especie) values ('Blue shark');
insert into especie (tipo_especie) values ('Marshbird, brown and yellow');
insert into especie (tipo_especie) values ('African buffalo');
insert into especie (tipo_especie) values ('Violet-crested turaco');
insert into especie (tipo_especie) values ('Oryx, beisa');
insert into especie (tipo_especie) values ('Cat, african wild');
insert into especie (tipo_especie) values ('Peccary, collared');
insert into especie (tipo_especie) values ('Wambenger, red-tailed');
insert into especie (tipo_especie) values ('Netted rock dragon');
insert into especie (tipo_especie) values ('Anteater, giant');
